{application,datetime_x_fin,
             [{description,"An datetime finance string manipulation library"},
              {vsn,"0.1.0"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[datetime_x,datetime_x_fin]},
              {maintainers,[]},
              {licenses,[]},
              {links,[]}]}.
